import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Navbar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import Header from '@/components/Header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Next Learn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen w-screen flex-col gap-3 antialiased`}
      >
        <SidebarProvider>
          <Navbar />
          <SidebarInset>
            <Header />
            <main className="flex-1">{children}</main>
            <footer className="self-center">
              <p>&copy; 2024 My Next.js App</p>
            </footer>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
